name: 'Setup Pub'
description: 'Setup the Dart Pub cache for the workflow'

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/cache
    - name: cache pub
      id: cache
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      env:
        cache-name: pub
      with:
        # pub-cache files are stored in `~/.pub-cache` on Linux/macOS
        path: ~/.pub-cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-

    - name: Path pub-cache
      shell: bash
      run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

    - name: Setup Melos
      shell: bash
      run: |
        dart pub global activate melos
        melos bootstrap
