import { autoGeneratedLabelComment } from "./constants";

/**
 * Resolves the index that serves as the boundary for auto-generation
 */
export function resolveAutoGeneratedIndex(contentLines: string[]): number {
  // Find the line that separates the auto-generated section
  let autoGeneratedIndex = contentLines.findIndex((line) =>
    line.includes(autoGeneratedLabelComment),
  );

  // If the auto-generated comment line is not found, treat everything up to the last line as manually generated
  if (autoGeneratedIndex === -1) {
    console.log(
      "Auto-generated label section not found.\n" +
        "Automatically generated from the end of the file.",
    );
    autoGeneratedIndex = contentLines.length;
  } else {
    console.log(
      `Auto-generated label section found on line ${autoGeneratedIndex + 1}.`,
    );
  }

  return autoGeneratedIndex;
}
